### ISSUE TITLE
Mengidentifikasi Penerima Kado dan preferensinya

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#10]

**Comment by milzam02** [comment]
Mengapa Orang Tua Baru Dipilih sebagai Penerima Kado:
1. Momen Istimewa:
   - Orang tua baru dipilih sebagai penerima kado karena kelahiran anak merupakan momen istimewa yang layak untuk dirayakan dan dihargai.
2. Dukungan Emosional:
   - Pemberian kado kepada orang tua baru bertujuan memberikan dukungan emosional dan kegembiraan di fase baru dalam kehidupan mereka.
3. Perawatan dan Dedikasi:
   - Orang tua baru dihargai atas perawatan dan dedikasi mereka dalam merawat dan membesarkan bayi, sehingga kado menjadi ungkapan apresiasi.
4. Kebutuhan Praktis:
   - Kado dipilih sebagai solusi praktis untuk membantu orang tua baru dalam mengatasi tugas-tugas sehari-hari merawat bayi, menciptakan kenyamanan dan kemudahan.
   
preferensi utama:
1. Gaya Hidup :
   - Sesuaikan kado dengan gaya hidup mereka, apakah aktif, petualang, atau lebih suka suasana yang tenang.
2. Warna dan Desain:
   - Pilih kado dengan warna dan desain yang sesuai dengan preferensi estetika rumah atau pribadi mereka.
3. Kebutuhan Praktis:
   - Identifikasi kebutuhan praktis seperti perlengkapan mandi bayi atau pakaian fungsional untuk memudahkan perawatan.

**Comment by ArdanJaysen47** [comment]
1. Identifikasi point 1 & 5 cukup identik, pilih salah 1 saja sebagai "perayaan" atau "Peringatan". 
2.  preferensi "gaya hidup" bisa disesuaikan kembali, acuannya adalah plan/rencana orang tua tersebut saat menyambut kehadiran  calon anak
