### ISSUE TITLE
Wawancara

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#11]
Untuk memahami Kebutuhan dan permintaannya

**Comment by ArdanJaysen47** [comment]
Yang perlu dipersiapkan sebelum wawancara itu apa ?
1. daftar pertanyaan yg sesuai konteks
2. improvisasi pertanyaan / follow up pertanyaan guna mendapatkan info tambahan yg mungkin berguna
3. Transkrip wawancara guna dokumentasi, bila perlu catat poin penting yang disampaikan atau tandai menit pada perekaman yang mengandung info penting.

**Comment by milzam02** [comment]
Transkrip Wawancara
Business analyst: assalamu alaikum warahmatullahi wabarakatuh.
Stakeholder: waalaikum salam warahmatullahi wabarakatuh.
Business analyst: kami di sini ada tugas untuk mewawancarai mengenai produk bayi.
Stakeholder: iya.
Business analyst: yah, jadi ada beberapa pertanyaan, baik pertanyaan pertama yaitu
Business analyst: kado seperti apa yang di inginkan seorang ibu ketika baru melahirkan?
Stakeholder: oh iya seperti perlengkapan bayi semisal sabun dll, popoklah ya.
Business analyst: langsung pertanyaan kedua bude, apa alasan memilih barang itu bude?
Stakeholder: karna sangat di butuhkan.
Business analyst: kemudian desain untuk kadonya bagusnya bagaimana, misalnya kami kasih kotak keren nya atau bagusnya bagaimana?
Stakeholder: ya mungkin lebih ke warna yang semisal cewe pink lah atau cowo biru.
Business analyst: untuk spesifikasi kayak ukuran baju atau motifnya bagusnya bagaimana bude.
Stakeholder: ya itu kalo cewe ya ke pink atau ke kuning kalo cowo ya sesuai anaknya atau yang lebih lembut warnanya untuk bayi.
Business analyst: ya mungkin itu saja, ya segitu saja bude, makasih bude, assalamu alaikum warahmatullahi wabarakatuh.
Stakeholder: ya waalaikum salam.
