### ISSUE TITLE
Merancang Konsep kado 

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#12]
Berdasarkan informasi dari analisis

**Comment by ArdanJaysen47** [comment]
setelah dapat poin penting hasil wawancara segera tentukan konsep hadiah yg akan diberikan. sumber acuan bisa berdasarkan tujuan & indentifikasi pada proses sebelumnya. jangan lupa konsultasikan dengan project owner tentang rancangan konsep.

**Comment by VALENTINO16023** [comment]
![desain](https://github.com/FajarTeguhPermana/project/assets/155214870/c591346f-7aca-42fe-8ad9-1396fb2f8266)

berdasarkan wawancara ada 2 tipe desain
 1.warna biru untuk anak cowo
2.warna pink buat anak cewe
desain dapat berubah rubah namun warna tetap sama, ini agar desain tidak monoton dan banyak pilihan
desain pita juga dapat berubah rubah namun warna tetap sama.

**Comment by ArdanJaysen47** [comment]
Jangan lupa desain kartu ucapan ya.
