### ISSUE TITLE
Menentukan jenis bahan dan alat yang di perlukan

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#13]

**Comment by ArdanJaysen47** [comment]
"siapkan" bahan bahan & alat yg diperlukan, tentunkan bagaimana cara pembuatan juga model pembuatan. bila diperlukan cari referensi yg pas sesuai konsep dan planning guna mempercepat pembuatan.

**Comment by VALENTINO16023** [comment]
bahan : 
1,kardus bekas
2.pita
3.kertas kado

alat : 
1.gunting
2.penggaris
3.lem kertas
4.selotip
5.pesil

cara pembuatan : 
1. Ambil kardus bekas dan gunting sesuai dengan ukuran yang diinginkan untuk kotak kado.
2. Gunakan penggaris untuk membantu memotong kardus dengan rapi.
3. Lipat kardus sesuai dengan bentuk kotak yang diinginkan dan rekatkan bagian tepinya menggunakan perekat.
4. Gunting pita sesuai panjang yang diinginkan untuk menghias kotak kado.
5. Bungkus kotak dengan kertas kado dan rekatkan dengan perekat.
6. Hiasi kotak dengan pita yang sudah dipotong sebelumnya.
7. Pastikan semua bagian terpasang dengan rapi

**Comment by FajarTeguhPermana** [comment]
mungkin lebih baik menggunakan kertas karton daripada kardus

**Comment by ArdanJaysen47** [comment]
penggunaan bahan disesuaikan lagi sesuai kebutuhan, misalkan kriterianya tahan penyok bila dijatuhkan dari ketinggian 1 meter, bahan kuat & kaku sehingga tidak berubah bentuk saat digengam 2 tangan, dll.
