### ISSUE TITLE
Membeli dan mengumpulkan alat yang diperlukan

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#14]

**Comment by ArdanJaysen47** [comment]
dokumentasikan proses pembuatan, sertakan panduan pembuatan yang bisa dibaca bila diperlukan

**Comment by VALENTINO16023** [comment]
Alat :
1. Gunting      harga : Rp 6.000
2. Selotip        harga : Rp 2.000
3. Lem Kertas harga : Rp 6.000
4. Pensil         harga : Rp 3.000
5. Penggaris   harga : Rp 4.000
