### ISSUE TITLE
Memastikan Kado sesuai dengan permintaan dan kebutuhan

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#16]

**Comment by ArdanJaysen47** [comment]
yg harus dilakukan apa ?
1. lakukan komunikasi dengan project terkait kecocokan desain
2. menguji kualitas bahan yang digunakan
3. periksa ketersediaan barang sesuai list/daftar kebutuhan yang tersedia
4. jika terdapat kekurangan segera catat dan laporkan kepada project owner

**Comment by ZulFauziHanif** [comment]
kekurangan yang harus dilengkapi : 
1. membuat kartu ucapan selamat semenarik dan sekreatif mungkin untuk orang yang menerima kado tersebut agar dapat menambah nilai sentimental dan personal pada hadiah yang diberikan.
2. dikarenakan kado ini diperuntukkan untuk perlengkapan bayi yang berisikan beberapa barang, maka diperlukan untuk memperkuat kemasan kado yang kokoh untuk dapat memberikan perlindungan tambahan terhadap tekanan, benturan, atau faktor-faktor lain yang dapat merusak isinya. seperti men-double lem/lakban untuk memperkuat kado agar memenuhi sesuai kapasitasnya, dll.
