### ISSUE TITLE
Membuat Kado sesuai dengan desain yang di rancang

### ISSUE THREAD

**Issue by FajarTeguhPermana** [FajarTeguhPermana/project#19]

**Comment by Zauro25** [comment]
![WhatsApp Image 2024-01-15 at 12 29 12](https://github.com/FajarTeguhPermana/project/assets/155167962/3e8a4fed-1628-4314-a5e7-ea54c420952f)

**Comment by FajarTeguhPermana** [comment]
oke, baguss
